/**
 * Centralized utility for cleaning and validating database queries generated by LLMs.
 */
function sanitizeSQL(rawSql) {
  if (!rawSql) return "";

  // 1. Strip markdown blocks
  let sql = rawSql
    .replace(/```sql/gi, "")
    .replace(/```/g, "")
    .trim();

  // 2. Extract ONLY the first SELECT block (to remove conversational noise)
  const selectMatch = sql.match(/SELECT[\s\S]*?(?:;|$)/i);
  if (selectMatch) {
    sql = selectMatch[0].trim();
  }

  // 3. Remove common SQL injection-like or prose patterns if they leaked
  sql = sql
    .split("\n")
    .filter(
      (line) => !line.trim().startsWith("--") && !line.trim().startsWith("/*"),
    )
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();

  return sql;
}

function sanitizeMQL(rawMql) {
  if (!rawMql) return null;

  try {
    // If it's already an object, return it
    if (typeof rawMql === "object") return rawMql;

    // 1. Strip markdown
    const cleanJson = rawMql
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();

    return JSON.parse(cleanJson);
  } catch (e) {
    console.error("[Query Sanitizer] MQL Parsing failed:", e.message);
    return null;
  }
}

module.exports = { sanitizeSQL, sanitizeMQL };
